galaxy_info:
  author: Jacob Hunt
  description: Create an OpenSSL root Certificate Authority

  license: GPL-3.0-only

  min_ansible_version: "2.9.10"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags:
    - openssl
    - certficateauthority
    - rootca

dependencies: []
